var Store = require('flux/utils').Store;
var SequencerDispatcher = require('../dispatcher/Dispatcher');
var SequencerStore = new Store(SequencerDispatcher);
var DrumStore = require('./DrumStore');

SequencerStore.bank = function (bankNum) {
  var returnBank = {};
  Object.keys(_banks[bankNum]).forEach(function (key) {
    returnBank[key] = _banks[bankNum][key];
  });
  return returnBank;
};

SequencerStore.currentBank = function () {
  return currentBank;
};

SequencerStore.__onDispatch = function (payload) {
  switch (payload.actionType) {
    case "UPDATE_BANK":
      updateBank(payload.bank, payload.drum, payload.beat);
      this.__emitChange();
      break;
    case "SWITCH_BANK":
      switchBank(payload.bank);
      this.__emitChange();
      break;
  }
};

function switchBank(bankNum) {
  currentBank = bankNum;
}

function updateBank(beat) {
  var bank = SequencerStore.currentBank();
  var drum = DrumStore.drum().name;

  _banks[bank][drum][beat - 1] = !_banks[bank][drum][beat - 1];
}

var currentBank = 1;

var _banks = {
  1: {
    bass: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    snare: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hihat: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hitom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    midtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    lowtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    ride: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    crash: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
  },
  2: {
    bass: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    snare: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hihat: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hitom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    midtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    lowtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    ride: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    crash: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
  },
  3: {
    bass: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    snare: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hihat: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hitom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    midtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    lowtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    ride: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    crash: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
  },
  4: {
    bass: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    snare: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hihat: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hitom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    midtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    lowtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    ride: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    crash: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
  },
  5: {
    bass: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    snare: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hihat: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hitom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    midtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    lowtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    ride: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    crash: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
  },
  6: {
    bass: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    snare: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hihat: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hitom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    midtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    lowtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    ride: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    crash: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
  },
  7: {
    bass: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    snare: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hihat: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hitom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    midtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    lowtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    ride: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    crash: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
  },
  8: {
    bass: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    snare: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hihat: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hitom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    midtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    lowtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    ride: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    crash: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
  },
  9: {
    bass: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    snare: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hihat: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hitom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    midtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    lowtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    ride: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    crash: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
  },
  10: {
    bass: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    snare: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hihat: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hitom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    midtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    lowtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    ride: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    crash: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
  },
  11: {
    bass: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    snare: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hihat: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hitom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    midtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    lowtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    ride: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    crash: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
  },
  12: {
    bass: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    snare: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hihat: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hitom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    midtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    lowtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    ride: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    crash: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
  },
  13: {
    bass: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    snare: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hihat: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hitom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    midtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    lowtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    ride: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    crash: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
  },
  14: {
    bass: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    snare: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hihat: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hitom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    midtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    lowtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    ride: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    crash: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
  },
  15: {
    bass: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    snare: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hihat: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hitom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    midtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    lowtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    ride: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    crash: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
  },
  16: {
    bass: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    snare: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hihat: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    hitom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    midtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    lowtom: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    ride: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
    crash: [false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false],
  },
};

module.exports = SequencerStore;
